project:
  type: website

website:
  title: "ECONTRIX 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day1/index.qmd
        text: Day 1
      - href: day2/index.qmd
        text: Day 2

format:
  html:
    theme:
      - yeti
      - tweaks.scss
    toc: true
brand: brand.yml



