[project]
name = "flame-economiga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "polars>=1.36.1",
    "pyjanitor>=0.32.8",
    "requests>=2.32.5",
]
